config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tests do
    resources :questions, shallow: true
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct_answers, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_number_of_answers, on: :create

  private

  def validate_number_of_answers
    message = 'Number of answers should be between 1..4'
    errors.add :base, :invalid, message: message if question.answers.count > 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: { message: "title category can't be blank" }
  validates :title, uniqueness: { message: 'category with this title already exists' }
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true, length: { minimum: 10 }
  validates_uniqueness_of :body, message: 'The question already exists!'
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category
  has_many :questions
  belongs_to :author, class_name: 'User'
  has_many :user_tests
  has_many :users, through: :user_tests

  scope :tests_by_category, ->(category) { joins(:category).where(categories: { title: category }) }
  scope :tests_entry_level, -> { where(level: 0..1) }
  scope :tests_middle_level, -> { where(level: 2..4) }
  scope :tests_advanced_level, -> { where(level: 5..FLOAT::INFINITY) }

  validates :level, numericality: { only_integer: true }
  validates :title, presence: true, uniqueness: { scope: :level,
                                                  message: 'test with this name and level already exists' }

  def self.tests_title_by_category(category)
    tests_by_category(category).order(title: :asc).pluck(:title)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id
  has_many :user_tests
  has_many :tests, through: :user_tests

  validates :name, :password, :e_mail, presence: true

  def tests_by_level(level)
    tests.where(level: level)
  end
end

app/models/user_test.rb
class UserTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :find_test, only: %i[new index create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :object_not_found

  def index
    redirect_to test_questions_path
  end

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @test
    else
      render inline: '<strong>The question is not was created!</strong>'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question.test
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    @question.destroy
    render plain: 'Question was deleted!'
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def object_not_found
    render plain: 'Object not found!'
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :all_tests, only: %i[show index]
  before_action :find_test, only: %i[show]

  def index; end

  def show; end

  private

  def all_tests
    @tests = Test.all
  end

  def find_test
    @test = @tests.find(test_params[:id])
  end

  def test_params
    params.permit(:title, :id, :level)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def github_url(author, repo)
    link_to 'TestGuru Project', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def current_year
    Time.now.year
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} Question"
    else
      "Create New #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  def levels
    { 'entry' => (0..1), 'middle' => (2..4), 'advanced' => (5..10) }
  end

  def test_level(level)
    levels.select { |k, v| v.include?(level) }.keys.first
  end
end

app/views/answers/_answers.html.erb
<table>
  <tr>
    <th>Answers</th>
    <th colspan='2'>Actions</th>
  </tr>
  <% @question.answers.each do |answer| %>
    <tr>
      <td><%= link_to answer.body %></td>
      <td><%= link_to 'Edit' %></td>
      <td><%= link_to 'Delete'%></td>
    </tr>
  <%end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<section class="content-wrapper">
  <div class="content-container">
    <%= yield %>
  </div>
</section>
<%= render "shared/footer" %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: [@test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %>
    <%= form.text_field :body, id: :question_body %>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/questions/_questions.html.erb
<table>
  <tr>
    <th>Questions</th>
    <th colspan='2'>Actions</th>
  </tr>
  <% @test.questions.each do |question| %>
    <tr>
      <td><%= link_to question.body, question_path(question) %></td>
      <td><%= link_to 'Edit', edit_question_path(question)%></td>
      <td><%= link_to 'Delete', question_path(question),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <%end %>
</table>

app/views/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>

<%= render 'form' %>
<%= link_to 'Back', test_path(@question.test_id) %>

app/views/questions/new.html.erb
<h1><%= question_header(@question) %></h1>
<%= render 'form' %>
<%= link_to 'Back', tests_path(@question.test_id) %>

app/views/questions/show.html.erb
<p>
  <strong> Question title: </strong>
  <tr><%= @question.body %></tr>
</p>

<tr><%= link_to 'Back', test_path(@question.test_id) %></tr>
<tr><%= link_to 'New answer'%></tr>
<%= render 'answers/answers'%>

app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    <div class="footer-container">
      <p class="footer_current-year"><%= current_year %></p>
      <p class="footer_author-name">Aleh Razanka (C)</p>
      <p class="footer_project"><%= github_url("Rezankozzi", "TestGuru") %></p>
      <p>Creating, managing and solving tests.<p>
      <p class="footer_school"><a href="https://thinknetica.com" class="footer_project-name--link">Учебный проект в онлайн-школе Thinknetica</a></p>
    </div>
  </div>
</footer>